#ifndef BIBA_PROTO_H
#define BIBA_PROTO_H

/* Wire protocol between the SBC (SPI master) and the STM32 (SPI slave).
 *
 * The protocol is full-duplex: each SPI transaction exchanges one
 * BIBA_PROTO_FRAME_SIZE-byte request from the SBC with one
 * BIBA_PROTO_FRAME_SIZE-byte telemetry reply pre-loaded by the STM32.
 *
 * Frame layout (fixed BIBA_PROTO_FRAME_SIZE bytes):
 *
 *    offset  size  field
 *    ------  ----  ----------------------------------------------------
 *        0      2  sync            (BIBA_PROTO_SYNC_0, BIBA_PROTO_SYNC_1)
 *        2      1  version         (BIBA_PROTO_VERSION)
 *        3      1  cmd             (biba_proto_cmd_t / biba_proto_tlm_t)
 *        4      1  seq             (monotonic sender counter)
 *        5      1  flags           (bitfield, bit0 = failsafe)
 *        6      1  payload_len     (0..BIBA_PROTO_PAYLOAD_MAX)
 *        7      1  reserved        (must be 0)
 *        8     54  payload         (command-specific)
 *       62      2  crc16           (CRC-16/CCITT-FALSE over bytes 0..61)
 *
 * The CRC polynomial is 0x1021 with init 0xFFFF, no input/output reflect,
 * and no final XOR. The same implementation lives in Python in
 * biba-controller/stm32_link/protocol.py so the two sides stay bit-for-bit
 * compatible. Native unit tests (test/test_biba_proto/) verify the C
 * implementation against fixed vectors; tests/test_stm32_link_protocol.py
 * verifies the Python side agrees.
 */

#include <stddef.h>
#include <stdint.h>

#include "biba_version.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BIBA_PROTO_FRAME_SIZE     64
#define BIBA_PROTO_HEADER_SIZE    8
#define BIBA_PROTO_CRC_SIZE       2
#define BIBA_PROTO_PAYLOAD_MAX    (BIBA_PROTO_FRAME_SIZE - BIBA_PROTO_HEADER_SIZE - BIBA_PROTO_CRC_SIZE)

#define BIBA_PROTO_SYNC_0         0xBAu
#define BIBA_PROTO_SYNC_1         0xBBu

/* Flags bitfield used in both directions. */
#define BIBA_PROTO_FLAG_FAILSAFE      (1u << 0)
#define BIBA_PROTO_FLAG_ARMED         (1u << 1)
#define BIBA_PROTO_FLAG_CRSF_ALIVE    (1u << 2)
#define BIBA_PROTO_FLAG_CURRENT_LIMIT (1u << 3)
#define BIBA_PROTO_FLAG_POWER_LIMIT   (1u << 4)

/* Commands from SBC -> STM32. */
typedef enum {
    BIBA_CMD_PING             = 0x01,
    BIBA_CMD_SET_SETPOINT     = 0x10,
    BIBA_CMD_GET_TELEMETRY    = 0x11,
    BIBA_CMD_ARM              = 0x20,
    BIBA_CMD_DISARM           = 0x21,
    BIBA_CMD_SET_CONFIG       = 0x30,
    /* Per-channel motor-audio PWM. BiBa has no buzzer — audible feedback
     * is generated by modulating the BTS7960 wheel PWMs. Payload is a
     * batch update of all four motor-PWM channels (see
     * biba_proto_motor_audio_t below). Targets without
     * BIBA_TARGET_HAS_PER_CHANNEL_TIMER_PWM accept the command but
     * silently ignore it. */
    BIBA_CMD_SET_MOTOR_AUDIO  = 0x40
} biba_proto_cmd_t;

/* Channel index used by BIBA_CMD_SET_MOTOR_AUDIO and the HAL audio API. */
typedef enum {
    BIBA_MOTOR_AUDIO_CH_LEFT_RPWM  = 0,
    BIBA_MOTOR_AUDIO_CH_LEFT_LPWM  = 1,
    BIBA_MOTOR_AUDIO_CH_RIGHT_RPWM = 2,
    BIBA_MOTOR_AUDIO_CH_RIGHT_LPWM = 3,
    BIBA_MOTOR_AUDIO_CH_COUNT      = 4
} biba_motor_audio_channel_t;

/* Flag bits in biba_proto_motor_audio_t.flags. */
#define BIBA_MOTOR_AUDIO_FLAG_AUDIO_MODE      (1u << 0)
#define BIBA_MOTOR_AUDIO_FLAG_OUTPUTS_ENABLE  (1u << 1)

/* Telemetry frame identifiers returned on the MISO line. */
typedef enum {
    BIBA_TLM_PONG      = 0x81,
    BIBA_TLM_SNAPSHOT  = 0x82,
    BIBA_TLM_ERROR     = 0x8F
} biba_proto_tlm_t;

/* Parse/build result codes. */
typedef enum {
    BIBA_PROTO_OK                   = 0,
    BIBA_PROTO_ERR_SIZE             = -1,
    BIBA_PROTO_ERR_SYNC             = -2,
    BIBA_PROTO_ERR_VERSION          = -3,
    BIBA_PROTO_ERR_PAYLOAD_TOO_BIG  = -4,
    BIBA_PROTO_ERR_CRC              = -5,
    BIBA_PROTO_ERR_ARGS             = -6
} biba_proto_status_t;

typedef struct {
    uint8_t version;
    uint8_t cmd;             /* command code (direction-dependent) */
    uint8_t seq;             /* sender sequence counter */
    uint8_t flags;           /* BIBA_PROTO_FLAG_* */
    uint8_t payload_len;     /* 0..BIBA_PROTO_PAYLOAD_MAX */
    uint8_t payload[BIBA_PROTO_PAYLOAD_MAX];
} biba_proto_frame_t;

/* CRC-16/CCITT-FALSE (poly=0x1021, init=0xFFFF, no reflect, xorout=0). */
uint16_t biba_proto_crc16_ccitt(const uint8_t *data, size_t len);

/* Serialize `frame` into the fixed BIBA_PROTO_FRAME_SIZE-byte `buffer`.
 * Returns BIBA_PROTO_OK on success. Fills reserved byte and CRC. */
int biba_proto_encode(const biba_proto_frame_t *frame,
                      uint8_t *buffer,
                      size_t buffer_len);

/* Validate and decode a raw BIBA_PROTO_FRAME_SIZE-byte frame into `frame`. */
int biba_proto_decode(const uint8_t *buffer,
                      size_t buffer_len,
                      biba_proto_frame_t *frame);

#pragma pack(push, 1)
typedef struct {
    uint16_t freq_hz[BIBA_MOTOR_AUDIO_CH_COUNT];  /* 0 = channel silent */
    uint8_t  duty_q8[BIBA_MOTOR_AUDIO_CH_COUNT];  /* 0..255 → 0..100 % */
    uint8_t  flags;                               /* BIBA_MOTOR_AUDIO_FLAG_* */
} biba_proto_motor_audio_t;
#pragma pack(pop)

/* Telemetry payload packed into the BIBA_TLM_SNAPSHOT frame. Laid out
 * little-endian explicitly so host tooling can unpack with struct.unpack. */
#pragma pack(push, 1)
typedef struct {
    int16_t  setpoint_left_q15;     /* echo of last accepted setpoint, -1..+1 */
    int16_t  setpoint_right_q15;
    int16_t  current_left_ma;       /* signed milliamps */
    int16_t  current_right_ma;
    uint16_t vbat_mv;               /* battery voltage, millivolts */
    uint16_t rail_12v_mv;           /* optional 12 V rail voltage */
    int16_t  gyro_x_cdps;           /* centi-degrees / second */
    int16_t  gyro_y_cdps;
    int16_t  gyro_z_cdps;
    int16_t  accel_x_mg;            /* milli-g */
    int16_t  accel_y_mg;
    int16_t  accel_z_mg;
    uint8_t  crsf_rssi;             /* uplink RSSI, raw CRSF units */
    uint8_t  crsf_link_quality;     /* LQ percent */
    int8_t   crsf_snr_db;           /* signal-to-noise, dB */
    uint8_t  error_flags;           /* BIBA_PROTO_FLAG_* snapshot */
    uint32_t uptime_ms;
    uint8_t  reserved[16];          /* pad to 48 bytes */
} biba_proto_telemetry_t;
#pragma pack(pop)

/* Convenience helper: build a telemetry reply frame. */
int biba_proto_encode_telemetry(uint8_t seq,
                                uint8_t flags,
                                const biba_proto_telemetry_t *tlm,
                                uint8_t *buffer,
                                size_t buffer_len);

#ifdef __cplusplus
}
#endif

#endif /* BIBA_PROTO_H */
