#ifndef BIBA_TARGET_H
#define BIBA_TARGET_H

/* Target: BIBA_F103_REV_A
 *
 * Reference custom PCB ("BiBa Driver Rev A") built around an STM32F103C8T6.
 * The Rev A pinout is driven by a single design constraint: BiBa has no
 * buzzer — audible feedback (voice / melodies / BLHeli-style tones) is
 * generated by directly modulating the BTS7960 wheel PWMs. To play four
 * independent voices at four independent frequencies we need each of the
 * four motor PWM lines on its own hardware timer, otherwise the shared
 * ARR forces one carrier across all of them.
 *
 * One timer per line:
 *   L_RPWM -> TIM1_CH1  (PA8,  default AF)
 *   L_LPWM -> TIM2_CH1  (PA15, TIM2 partial remap 1; JTAG already released)
 *   R_RPWM -> TIM3_CH4  (PB1,  default AF)
 *   R_LPWM -> TIM4_CH4  (PB9,  default AF)
 *
 * In traction mode the HAL layer points all four timers at the same
 * BIBA_PWM_FREQUENCY_HZ carrier and only changes the compare values, so
 * BTS7960 drive is byte-compatible with a one-timer board.
 *
 * Other differences from BLUEPILL_F103C8:
 *   - Dedicated op-amp shunt (10 A/V, 0 V offset).
 *   - MODE_SEL re-homes to PA7 because PB9 is taken by TIM4_CH4.
 *   - PA5 is a chassis-temperature NTC, not a 12 V rail tap.
 *   - PA9/PA10/PA11 are left as no-connects on the PCB; the MCU releases
 *     them as GPIOs (formerly TIM1_CH2..CH4).
 *
 * The test-matrix point of this target is still to make sure that
 * adding a new board never touches the portable code — only these three
 * files.
 */

#define BIBA_TARGET_NAME            "BIBA_F103_REV_A"
#define BIBA_TARGET_HAS_BTS7960_2CH 1
#define BIBA_TARGET_HAS_CRSF        1
#define BIBA_TARGET_HAS_IMU         1
#define BIBA_TARGET_HAS_SPI_SLAVE   1
#define BIBA_TARGET_HAS_CHASSIS_NTC 1

/* Four independent timers, one per motor PWM line -> four independent
 * carriers, which the motor-audio HAL uses to play sound through the
 * wheels. */
#define BIBA_TARGET_HAS_PER_CHANNEL_TIMER_PWM 1

#if !defined(BIBA_NATIVE_TEST)
#  include "stm32f1xx_hal.h"
#endif

/* --- Motor PWM (per-channel timers) ------------------------------------ */

/* Left R_PWM: PA8 / TIM1_CH1 (default AF). */
#define BIBA_PIN_LEFT_RPWM_PORT          GPIOA
#define BIBA_PIN_LEFT_RPWM_PIN           GPIO_PIN_8
#define BIBA_PWM_LEFT_RPWM_TIM           TIM1
#define BIBA_PWM_LEFT_RPWM_CHANNEL       TIM_CHANNEL_1
#define BIBA_PWM_LEFT_RPWM_CLK_ENABLE()  __HAL_RCC_TIM1_CLK_ENABLE()
#define BIBA_PWM_LEFT_RPWM_AF_REMAP()    ((void)0)

/* Left L_PWM: PA15 / TIM2_CH1 via TIM2 partial remap 1. */
#define BIBA_PIN_LEFT_LPWM_PORT          GPIOA
#define BIBA_PIN_LEFT_LPWM_PIN           GPIO_PIN_15
#define BIBA_PWM_LEFT_LPWM_TIM           TIM2
#define BIBA_PWM_LEFT_LPWM_CHANNEL       TIM_CHANNEL_1
#define BIBA_PWM_LEFT_LPWM_CLK_ENABLE()  __HAL_RCC_TIM2_CLK_ENABLE()
#define BIBA_PWM_LEFT_LPWM_AF_REMAP()    __HAL_AFIO_REMAP_TIM2_PARTIAL_1()

/* Right R_PWM: PB1 / TIM3_CH4 (default AF). */
#define BIBA_PIN_RIGHT_RPWM_PORT         GPIOB
#define BIBA_PIN_RIGHT_RPWM_PIN          GPIO_PIN_1
#define BIBA_PWM_RIGHT_RPWM_TIM          TIM3
#define BIBA_PWM_RIGHT_RPWM_CHANNEL      TIM_CHANNEL_4
#define BIBA_PWM_RIGHT_RPWM_CLK_ENABLE() __HAL_RCC_TIM3_CLK_ENABLE()
#define BIBA_PWM_RIGHT_RPWM_AF_REMAP()   ((void)0)

/* Right L_PWM: PB9 / TIM4_CH4 (default AF). */
#define BIBA_PIN_RIGHT_LPWM_PORT         GPIOB
#define BIBA_PIN_RIGHT_LPWM_PIN          GPIO_PIN_9
#define BIBA_PWM_RIGHT_LPWM_TIM          TIM4
#define BIBA_PWM_RIGHT_LPWM_CHANNEL      TIM_CHANNEL_4
#define BIBA_PWM_RIGHT_LPWM_CLK_ENABLE() __HAL_RCC_TIM4_CLK_ENABLE()
#define BIBA_PWM_RIGHT_LPWM_AF_REMAP()   ((void)0)

/* --- Motor enables (GPIO, JTAG already released) ----------------------- */

#define BIBA_PIN_LEFT_REN_PORT       GPIOB
#define BIBA_PIN_LEFT_REN_PIN        GPIO_PIN_3    /* freed from JTDO */
#define BIBA_PIN_LEFT_LEN_PORT       GPIOB
#define BIBA_PIN_LEFT_LEN_PIN        GPIO_PIN_4    /* freed from NJTRST */
#define BIBA_PIN_RIGHT_REN_PORT      GPIOB
#define BIBA_PIN_RIGHT_REN_PIN       GPIO_PIN_5
#define BIBA_PIN_RIGHT_LEN_PORT      GPIOB
#define BIBA_PIN_RIGHT_LEN_PIN       GPIO_PIN_8

/* --- ADC1 scan --------------------------------------------------------- */

#define BIBA_ADC_CHAN_LEFT_R_IS      0U   /* PA0 */
#define BIBA_ADC_CHAN_LEFT_L_IS      1U   /* PA1 */
#define BIBA_ADC_CHAN_RIGHT_R_IS     2U   /* PA2 */
#define BIBA_ADC_CHAN_RIGHT_L_IS     3U   /* PA3 */
#define BIBA_ADC_CHAN_VBAT           4U   /* PA4 */
#define BIBA_ADC_CHAN_RAIL_12V       5U   /* PA5 — used as chassis NTC */
#define BIBA_ADC_CHAN_RAIL_CURRENT   6U   /* PA6 */

#define BIBA_ADC_SCAN_LEN            7U

/* --- CRSF (USART3) ---------------------------------------------------- */

#define BIBA_PIN_CRSF_TX_PORT        GPIOB
#define BIBA_PIN_CRSF_TX_PIN         GPIO_PIN_10
#define BIBA_PIN_CRSF_RX_PORT        GPIOB
#define BIBA_PIN_CRSF_RX_PIN         GPIO_PIN_11

/* --- SPI slave (SPI2) ------------------------------------------------- */

#define BIBA_PIN_SPI_NSS_PORT        GPIOB
#define BIBA_PIN_SPI_NSS_PIN         GPIO_PIN_12
#define BIBA_PIN_SPI_SCK_PORT        GPIOB
#define BIBA_PIN_SPI_SCK_PIN         GPIO_PIN_13
#define BIBA_PIN_SPI_MISO_PORT       GPIOB
#define BIBA_PIN_SPI_MISO_PIN        GPIO_PIN_14
#define BIBA_PIN_SPI_MOSI_PORT       GPIOB
#define BIBA_PIN_SPI_MOSI_PIN        GPIO_PIN_15

/* --- Data-ready line to SBC ------------------------------------------- */

#define BIBA_PIN_DATA_READY_PORT     GPIOA
#define BIBA_PIN_DATA_READY_PIN      GPIO_PIN_12

/* --- Mode select ------------------------------------------------------- */

/* MODE_SEL moved to PA7 because PB9 is now TIM4_CH4 / R_LPWM. PA7 is
 * still free: PA6 is ADC_IN6 (rail current), PA7 has no fixed-function
 * use on this board so it's available for a pull-up + external switch. */
#define BIBA_PIN_MODE_SEL_PORT       GPIOA
#define BIBA_PIN_MODE_SEL_PIN        GPIO_PIN_7

/* --- IMU (I2C1) ------------------------------------------------------- */

#define BIBA_PIN_I2C_SCL_PORT        GPIOB
#define BIBA_PIN_I2C_SCL_PIN         GPIO_PIN_6
#define BIBA_PIN_I2C_SDA_PORT        GPIOB
#define BIBA_PIN_I2C_SDA_PIN         GPIO_PIN_7

#define BIBA_PIN_IMU_INT1_PORT       GPIOB
#define BIBA_PIN_IMU_INT1_PIN        GPIO_PIN_2

/* --- Status LED ------------------------------------------------------- */

/* Reuse the same PC13 active-low footprint as BLUEPILL_F103C8 — simpler
 * BOM and the same HAL code path. The on-board Rev A indicator LED is
 * wired to PC13 on the new schematic. */
#define BIBA_PIN_STATUS_LED_PORT     GPIOC
#define BIBA_PIN_STATUS_LED_PIN      GPIO_PIN_13
#define BIBA_STATUS_LED_ACTIVE_LOW   1

#endif /* BIBA_TARGET_H */
