#!/usr/bin/env python3
"""Convert WAV files to C uint8_t arrays for embedding in RP2040 firmware.

Output file: src/app/pcm_sounds.h

Each sample is 8-bit unsigned (0..255), normalised to full range.
Source files are resampled to PCM_RATE Hz using nearest-neighbour decimation.
"""

import os
import struct
import wave

PCM_RATE = 8000   # target sample rate written to flash

VOICES = [
    ("pcm_arm",    "biba-controller/voice/arm_begin.wav"),
    ("pcm_disarm", "biba-controller/voice/disarm_waiting.wav"),
]

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT   = os.path.normpath(os.path.join(SCRIPT_DIR, "../.."))
OUT_PATH    = os.path.join(SCRIPT_DIR, "../src/app/pcm_sounds.h")


def load_wav_8bit_mono(path: str, target_rate: int = PCM_RATE) -> bytes:
    """Read a WAV, mix to mono, normalise to 0-255, resample to target_rate."""
    with wave.open(path, "rb") as wf:
        n_ch    = wf.getnchannels()
        sw      = wf.getsampwidth()
        src_rate = wf.getframerate()
        raw     = wf.readframes(wf.getnframes())

    # Decode to signed int list
    if sw == 2:
        total = len(raw) // 2
        samples = list(struct.unpack(f"<{total}h", raw))
    elif sw == 1:
        # 8-bit WAV is unsigned; shift to signed
        samples = [b - 128 for b in raw]
    else:
        raise ValueError(f"Unsupported sample width: {sw} bytes")

    # Mix stereo to mono
    if n_ch == 2:
        samples = [(samples[i] + samples[i + 1]) // 2
                   for i in range(0, len(samples) - 1, 2)]

    # Normalise: zero-mean centered at 128, then apply gain (>1.0 = overdrive).
    # Gain boosts RMS loudness at the cost of soft clipping on peaks.
    # This guarantees equal forward/reverse drive energy in bipolar PCM mode
    # → no net DC torque → wheels stay still during playback.
    GAIN = 6.0
    mean = sum(samples) / len(samples) if samples else 0.0
    peak = max(abs(v - mean) for v in samples) if samples else 1.0
    if peak == 0.0:
        peak = 1.0
    samples = [min(255, max(0, int(round((v - mean) * 127.0 * GAIN / peak + 128))))
               for v in samples]

    # Nearest-neighbour resample
    if src_rate != target_rate:
        out = []
        step = src_rate / target_rate
        idx = 0.0
        while int(idx) < len(samples):
            out.append(samples[int(idx)])
            idx += step
        samples = out

    return bytes(int(v) for v in samples)


def to_c_array(name: str, data: bytes, rate: int) -> str:
    lines = [
        f"/* {name}: {len(data)} samples @ {rate} Hz"
        f"  ({len(data) / rate:.2f} s) */",
        f"static const uint8_t  {name}_data[{len(data)}] = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += [
        "};",
        f"static const uint32_t {name}_count = {len(data)}u;",
        f"static const uint32_t {name}_rate  = {rate}u;",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    out_lines = [
        "#pragma once",
        "/* Auto-generated by tools/wav_to_c.py — do not edit manually. */",
        "#include <stdint.h>",
        "",
    ]

    for sym_name, rel_path in VOICES:
        abs_path = os.path.join(REPO_ROOT, rel_path)
        data = load_wav_8bit_mono(abs_path)
        out_lines.append(to_c_array(sym_name, data, PCM_RATE))
        print(f"  {sym_name}: {len(data)} samples"
              f" @ {PCM_RATE} Hz  ({len(data) / PCM_RATE:.2f} s)"
              f"  [{len(data)} bytes in flash]")

    with open(OUT_PATH, "w") as fh:
        fh.write("\n".join(out_lines))
    print(f"Written: {OUT_PATH}")


if __name__ == "__main__":
    main()
